numpy is a python package for doing efficient computation with arrays of numbers

In [1]:
# this way of importing numpy will let us refer to any functions from numpy as np.function
import numpy as np

In [5]:
# make a new array
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# make a new array linearly spaced from 0 to 90 that has 10 entries
y = np.linspace(0, 90, 10)
y

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.])

In [9]:
# we can do addition, multiplication, and most other numeric operations element-wise
x + y

array([  0.,  11.,  22.,  33.,  44.,  55.,  66.,  77.,  88.,  99.])

In [12]:
y - x

array([  0.,   9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  81.])

In [11]:
x * y

array([   0.,   10.,   40.,   90.,  160.,  250.,  360.,  490.,  640.,  810.])